CREATE DATABASE YANDM_STORE;
USE YANDM_STORE;


SET sql_safe_updates = 0; -- tắt chế độ bảo về mysql
DROP DATABASE YANDM_STORE;

CREATE TABLE ACCOUNTS(
	A_EMAIL	VARCHAR(255) PRIMARY KEY,
    A_PASSWORD VARCHAR(255) NOT NULL,
    A_ROLE	VARCHAR(5) DEFAULT 'user'
);

select * from ACCOUNTS;
delete from ACCOUNTS where a_email='admin@gmail.com';
insert into accounts values('admin@gmail.com',md5('admin123'),'admin');

CREATE TABLE USERS (
	U_ID INT PRIMARY KEY,
    A_EMAIL	VARCHAR(255) REFERENCES ACCOUNTS(A_EMAIL),
    U_NAME VARCHAR(50) NOT NULL,
    U_PHONE VARCHAR(10) NOT NULL UNIQUE,
    U_ADDRESS VARCHAR(255) DEFAULT NULL,
    U_AVT VARCHAR(255) DEFAULT NULL,
    U_CREATED_AT DATETIME DEFAULT NULL,
    U_UPDATED_AT DATETIME DEFAULT NULL,
    U_DELETED INT
);

CREATE TABLE CATEGORIES(
	C_ID VARCHAR(4) PRIMARY KEY,
    C_NAME VARCHAR(50) NOT NULL
);
SELECT * FROM CATEGORIES;

CREATE TABLE COLOR(
	CO_ID VARCHAR(3) PRIMARY KEY,
    CO_NAME VARCHAR(50) NOT NULL
);
SELECT * FROM COLOR;
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C01", "Black");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C02", "Blue");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C03", "Brown");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C04", "Burgundy");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C05", "Green");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C06", "Grey");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C07", "Ivory");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C08", "Orange");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C09", "Pink");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C10", "Yellow");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C11", "Red");
INSERT INTO COLOR(CO_ID, CO_NAME) VALUE ("C12", "White");

CREATE TABLE SIZES(
	S_ID VARCHAR(3) PRIMARY KEY,
    S_SIZES VARCHAR(4) NOT NULL
);
SELECT * FROM SIZES;
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S01", "XS");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S02", "S");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S03", "M");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S04", "L");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S05", "XL");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S06", "XXL");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S07", "36");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S08", "37");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S09", "38");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S10", "39");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S11", "40");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S12", "41");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S13", "42");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S14", "43");
INSERT INTO SIZES(S_ID, S_SIZES) VALUE ("S15", "44");

CREATE TABLE TEE_SHIRTS(
	T_ID VARCHAR(4),
    CO_ID VARCHAR(3) NOT NULL REFERENCES COLOR(CO_ID),
    S_ID VARCHAR(3) NOT NULL REFERENCES SIZES(S_ID),
    PRIMARY KEY (T_ID, CO_ID, S_ID),
    C_ID VARCHAR(4) NOT NULL REFERENCES CATEGORIES(C_ID),
    T_TITLE VARCHAR(255) NOT NULL,
    T_PRICE INT NOT NULL DEFAULT 0,
    T_DISCOUNT INT NOT NULL DEFAULT 0,
	T_ILLUSTRATION VARCHAR(255) NOT NULL,
    T_DESCRPTION LONGTEXT NOT NULL,
    T_QUANTITY INT NOT NULL DEFAULT 0,
    T_CREATED_AT DATETIME DEFAULT NULL,
    T_UPDATED_AT DATETIME DEFAULT NULL,
    T_DELETED INT
);
select * from SEARCH_RES;
select * from TEE_SHIRTS;
delete from TEE_SHIRTS;
SELECT T_ID, T_TITLE, CO_ID, S_ID, T_PRICE, T_DISCOUNT, T_ILLUSTRATION FROM TEE_SHIRTS ORDER BY T_ID DESC;

CREATE TABLE PANTS(
	P_ID VARCHAR(4),
    CO_ID VARCHAR(3) NOT NULL REFERENCES COLOR(CO_ID),
    S_ID VARCHAR(3) NOT NULL REFERENCES SIZES(S_ID),
    PRIMARY KEY (P_ID, CO_ID, S_ID),
    C_ID VARCHAR(4) NOT NULL REFERENCES CATEGORIES(C_ID),
    P_TITLE VARCHAR(255) NOT NULL,
    P_PRICE INT NOT NULL DEFAULT 0,
    P_DISCOUNT INT NOT NULL DEFAULT 0,
	P_ILLUSTRATION VARCHAR(255) NOT NULL,
    P_DESCRPTION LONGTEXT NOT NULL,
    P_QUANTITY INT NOT NULL,
    P_CREATED_AT DATETIME DEFAULT NULL,
    P_UPDATED_AT DATETIME DEFAULT NULL,
    P_DELETED INT
);
select * from PANTS;
delete from PANTS;
SELECT P_ID, P_TITLE, CO_ID, S_ID, P_PRICE, P_DISCOUNT, P_ILLUSTRATION FROM PANTS ORDER BY P_ID DESC;

CREATE TABLE SHOES(
	SH_ID VARCHAR(4),
    CO_ID VARCHAR(3) NOT NULL REFERENCES COLOR(CO_ID),
    S_ID VARCHAR(3) NOT NULL REFERENCES SIZES(S_ID),
    PRIMARY KEY (SH_ID, CO_ID, S_ID),
    C_ID VARCHAR(4) NOT NULL REFERENCES CATEGORIES(C_ID),
    SH_TITLE VARCHAR(255) NOT NULL,
    SH_PRICE INT NOT NULL DEFAULT 0,
    SH_DISCOUNT INT NOT NULL DEFAULT 0,
	SH_ILLUSTRATION VARCHAR(255) NOT NULL,
    SH_DESCRPTION LONGTEXT NOT NULL,
    SH_QUANTITY INT NOT NULL,
    SH_CREATED_AT DATETIME DEFAULT NULL,
    SH_UPDATED_AT DATETIME DEFAULT NULL,
    SH_DELETED INT
);
select * from SHOES;
delete from TEE_SHIRTS WHERE CO_ID='C11';
SELECT SH_ID, SH_TITLE, CO_ID, S_ID, SH_PRICE, SH_DISCOUNT, SH_ILLUSTRATION FROM SHOES ORDER BY SH_ID DESC;

CREATE TABLE ILLUSTRATIONS(
	I_ID VARCHAR(4) PRIMARY KEY,
    P_ID VARCHAR(4) NOT NULL REFERENCES PRODUCTS(P_ID),
    I_ILLUSTRATION VARCHAR(255) DEFAULT NULL
);

CREATE TABLE FEEDBACK(
	F_ID VARCHAR(4) PRIMARY KEY,
    F_NAME VARCHAR(50) NOT NULL,
    F_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    F_PHONE VARCHAR(10) NOT NULL UNIQUE,
    F_TITLENAME VARCHAR(100) NOT NULL,
    F_NOTE LONGTEXT DEFAULT NULL,
    F_CREATED_AT DATETIME DEFAULT NULL,
    F_UPDATED_AT DATETIME DEFAULT NULL
);

CREATE TABLE ORDERS(
	O_ID VARCHAR(4) PRIMARY KEY,
    U_ID VARCHAR(8) NOT NULL REFERENCES USERS(U_ID),
    O_NAME VARCHAR(50) NOT NULL,
    O_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    O_PHONE VARCHAR(10) NOT NULL UNIQUE,
    O_ADDRESS VARCHAR(255) DEFAULT NULL,
    O_NOTE LONGTEXT DEFAULT NULL,
    O_ORDERDATE DATETIME NOT NULL,
    O_STATUS INT NOT NULL,
    O_TOTAL FLOAT NOT NULL DEFAULT 0
    -- 0 : NGƯỜI BÁN ĐANG CHUẨN BỊ HÀNG
    -- 1 : ĐƠN HÀNG ĐANG ĐƯỢC GIAO
);

CREATE TABLE ORDER_DETAILS(
	OD_ID VARCHAR(6) PRIMARY KEY,
    O_ID VARCHAR(4) NOT NULL REFERENCES ORDERS(O_ID),
    P_ID VARCHAR(4) NOT NULL REFERENCES PRODUCTS(P_ID),
    OD_CURRENTPRICE INT NOT NULL DEFAULT 0,
    OD_QUANTITIES INT NOT NULL DEFAULT 0
);

ALTER TABLE USERS MODIFY U_ID INT NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

CREATE TABLE SEARCH_RES(
	SR_KEY VARCHAR(6) NOT NULL,
    SR_ID VARCHAR(4) NOT NULL
);

select * from users;
DELETE FROM SEARCH_RES;